### ISSUE TITLE
Cumhaz CI doesn't consider conf.level parameter

### ISSUE THREAD

**Issue by davidrosspainter** [seasamgo/optband#1]
Changing the value has no effect. Also where are these values stored? They come out of the plot automatically but I cannot work out how to access them.

**Comment by seasamgo** [comment]
Do you have a reproducible example? It's difficult to understand what you're seeing without one. 

Lines 270-273 in the R file show that we update the `lower` and `upper` values of the input `survfit` object, which is then returned on Line 282.

Considering this, I definitely see the values change between all scenarios across a range of `conf.level` options. My guess would be that you're then plotting with `plot(..., cumhaz = TRUE)` but that method is independent of ours and would recalculate the CIs on its own using the `survfit` object.

**Comment by seasamgo** [comment]
Hi! Thanks for using our package. Do you have a reproducible example? It's difficult to understand what you're seeing without one. 

Lines 270-273 in the R file show that we update the `lower` and `upper` values of the input `survfit` object, which is then returned on Line 282.

Considering this, I definitely see the values change between all scenarios across a range of `conf.level` options. My guess would be that you're then plotting with `plot(..., cumhaz = TRUE)` but that method is independent of ours and would recalculate the CIs on its own using the `survfit` object.
